# Evolution3DS Version Configuration
# This file defines the version numbers for Evolution3DS and the base Luma3DS version

EVOLUTION_VERSION_MAJOR := 1
EVOLUTION_VERSION_MINOR := 4
EVOLUTION_VERSION_BUILD := 2

LUMA_VERSION_MAJOR := 13
LUMA_VERSION_MINOR := 4
LUMA_VERSION_BUILD := 0

export EVOLUTION_VERSION_MAJOR
export EVOLUTION_VERSION_MINOR
export EVOLUTION_VERSION_BUILD
export LUMA_VERSION_MAJOR
export LUMA_VERSION_MINOR
export LUMA_VERSION_BUILD
